name: Build and Push CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn --batch-mode clean install

      - name: Upload Artifact codegen
        if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: javatoavalla-1.0-SNAPSHOT-jar-with-dependencies.jar
          path: target/javatoavalla-1.0-SNAPSHOT-jar-with-dependencies.jar
          retention-days: 1

  docker:
    name: Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: javatoavalla-1.0-SNAPSHOT-jar-with-dependencies.jar
          path: ./target

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: isaacmaffeis/javatoavalla:latest

      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v5.1.0
        with:
          name: javatoavalla-1.0-SNAPSHOT-jar-with-dependencies.jar
